queue_rules:
  - name: default
    merge_conditions:
      - check-success=buildbot/nix-build
      - check-success=tests (ubuntu-latest, stable)
      - check-success=tests (ubuntu-latest, latest)
      - check-success=tests (ubuntu-latest, bash4)
    batch_size: 5
    merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
